#!/bin/bash

apt-get update
apt-get upgrade
apt-get install apache2 -y
apt-get install unzip -y
apt-get install wget -y

echo "atualizaçao e intalaçao de dependecias"

cd /tmp
wget https://github.com/denilsonbonatti/linux-site-dio/archive/refs/heads/main.zip
unzip main.zip
cd linux-site-dio
cp -R * /var/www/html/

